name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: build
        run: ./gradlew jibDockerBuild --image=ghcr.io/neetkee/chatgpt-telegram-bot
      - name: push
        run: |
          echo ${{ secrets.REGISTRY_TOKEN }} | docker login ghcr.io -u neetkee --password-stdin
          docker push ghcr.io/neetkee/chatgpt-telegram-bot:latest
